name: Release

on:
  workflow_dispatch:

jobs:
  release:
    permissions:
      contents: write
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm run build

      - name: Install dependencies
        run: npm install
      # - name: Get Release Token
      #   id: get_workflow_token
      #   uses: peter-murray/workflow-application-token-action@v3
      #   with:
      #     application_id: ${{ secrets.RELEASE_APP_ID }}
      #     application_private_key: ${{ secrets.RELEASE_APP_CERT }}
      - name: Run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        #   NPM_TOKEN: ${{ secrets.NPM_TOKEN }} # if publishing to npm
        run: npx semantic-release
# name: Release

# on:
#   push:
#     branches:
#       - main

# jobs:
#   release:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3
#         with:
#           fetch-depth: 0 # Full history is needed for semantic-release

#       - name: Use Node.js
#         uses: actions/setup-node@v3
#         with:
#           node-version: 22 # or your preferred Node.js version

#       - name: Install dependencies
#         run: npm install

#       - name: Run semantic-release
#         env:
#           GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
#         #   NPM_TOKEN: ${{ secrets.NPM_TOKEN }} # if publishing to npm
#         run: npx semantic-release
